apiVersion: v1
kind: Secret
metadata:
  name: umg-assistance-registry-backend-secret
type: Opaque
stringData:
  # Clave secreta para Django. En producción, esta debe ser una cadena larga y segura.
  DJANGO_SECRET_KEY: "tu-clave-secreta-segura"

  # Variable de entorno para activar o desactivar el modo de depuración en Django. En producción, esto debe ser "False".
  DJANGO_DEBUG: "False"

  # Hosts permitidos para la aplicación Django. En producción, esto debe incluir el dominio de tu aplicación.
  DJANGO_ALLOWED_HOSTS: "tu-dominio.com,localhost,127.0.0.1"

  # Nombre de la base de datos.
  DB_NAME: "tu-nombre-de-base-de-datos-sql-server"

  # Usuario de la base de datos.
  DB_USER: "tu-usuario-sql-server"

  # Contraseña de la base de datos.
  DB_PASSWORD: "tu-contraseña-de-usuario-sql-server"

  # Host de la base de datos.
  DB_HOST: "tu-host-sql-server"

  # Puerto de la base de datos.
  DB_PORT: "tu-puerto-sql-server"

  # Correo electrónico del emisor para enviar los reportes de asistencia.
  EMAIL_EMISOR: "tu-correo-electrónico"

  # Ruta al archivo de certificado SSL en formato .pfx o .p12 para la firma digital de los reportes de asistencia.
  CERT_PATH: "ruta/al/archivo/certificado.pfx"

  # Contraseña del certificado SSL para acceder a la clave privada. Si el certificado no tiene contraseña, dejarlo vacío.
  CERT_PASSWORD: "tu-contraseña-del-certificado-ssl"
